name: lua test

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install lua
      run: |
        curl -OL https://nchc.dl.sourceforge.net/project/luabinaries/5.4.2/Tools%20Executables/lua-5.4.2_Win64_bin.zip
        7z x lua-5.4.2_Win64_bin.zip -olua
        $pwd=$(get-location).Path
        [Environment]::SetEnvironmentVariable("Path",[Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine) +";$pwd\lua",[EnvironmentVariableTarget]::Machine)
        lua.exe .\.github\workflows\getVersion.lua -code