name: lua test

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download lua
      run: |
        curl -OL https://nchc.dl.sourceforge.net/project/luabinaries/5.4.2/Tools%20Executables/lua-5.4.2_Win64_bin.zip
    - name: Unpack lua
      run: |
        7z x .\lua-5.4.2_Win64_bin.zip -olua
        rename-Item '.\lua\lua54.exe' -NewName 'lua.exe'
    - name: test
      run: |
        .\lua\lua.exe .\.github\workflows\getVersion.lua -updatename