name: release test

on: 
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      name: 
        description: '将要发布的版本名称'
        required: true
      body:
        description: 'release详细信息'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        name: ${{ github.event.inputs.name }}
        body: ${{ github.event.inputs.body }}
        with:
          files: Release.txt
