name: release test

on: 
  workflow_dispatch:
    inputs:
      name: 
        description: '将要发布的版本名称'
        required: true
      body:
        description: 'release详细信息'
        required: true
      tag: 
        description: 'release使用的tag'
        required: true

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > linux.txt
      - name: Test
        run: cat linux.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.name }}
          body: ${{ github.event.inputs.body }}
          files: linux.txt

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: echo ${{ github.sha }} > windows.txt
      - name: Test
        run: cat windows.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.name }}
          body: ${{ github.event.inputs.body }}
          files: windows.txt