name: CI test

on:
  push:
    branches: [ main ]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH connection to Actions
      uses: csexton/debugger-action@master