name: CI test

env: 
  git_hash: ${{ GITHUB.SHA }}

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        git_hash=$(git rev-parse --short "${{ GITHUB.SHA }}")
        ls
        mkdir test
        touch test.txt
        echo ${git_hash}233 > test.txt
        echo ${{ GITHUB.JOB }}233 >> test.txt
        echo ${{ GITHUB.ACTION }}233 >> test.txt
    - name: Update
      uses: actions/upload-artifact@v2
      with:
        name: Test_${{ env.git_hash }}
        path: test.txt