name: CI test

on:
  push:
    branches: [ main ]

jobs:
  test1: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        mkdir test
        cd test
        touch test.1
        touch test.2
    - uses: actions/upload-artifact@v2
      with:
        name: test
        path: test

  test2:
    runs-on: ubuntu-latest
    needs: [ test1 ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: test
    - uses: actions/download-artifact@v2
      with:
        name: test
        path: test
    - name: test
      run: |
        ls
        cd test
        ls
