name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 26F-Studio/cold_clear_ai_love2d_wrapper
          submodules: true
      - name: build in docker
        shell: docker run -it -v $(pwd):/work ubuntu:18.04 /bin/bash {0}
        run: |
          apt-get update
          apt-get install libluajit-5.1-dev curl build-essential
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y
          source "$HOME/.cargo/env"
          rustup target add x86_64-unknown-linux-gnu
          make build/Linux/x64/CCloader.so
          strip build/Linux/x64/CCloader.so
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: build/Linux
