name: CI test

on:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        git_hash=$(git rev-parse --short "${{ GITHUB.SHA }}")
        echo "git_hash=${git_hash}" >> $GITHUB_ENV
        mkdir test
        touch test.txt
        echo ${git_hash} > test.txt
    - name: Update
      uses: actions/upload-artifact@v2
      with:
        name: Test_${{ env.git_hash }}
        path: test.txt