name: CI test

on:
  push:
    branches: [ main ]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: touch file
      run: |
        touch a.txt
        touch b.txt
        touch c.txt
    - name: upload a
      uses: actions/upload-artifact@v3
        with:
          name: a
          path: a.txt
    - name: upload b
      uses: actions/upload-artifact@v3
        with:
          name: b
          path: b.txt
    - name: upload c
      uses: actions/upload-artifact@v3
        with:
          name: c
          path: c.txt
