name: CI test

on:
  push:
    branches: [ main ]

jobs:
  build-windows: 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        python .\.github\workflows\getLatest.py