name: Release CI

on:
  push:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: test install
        shell: bash
        run: |
          curl -L --retry 5 https://jrsoftware.org/download.php/is.exe -o is.exe
          ./is.exe /verysilent
          iscc /?
